server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tour_bot
    username: postgres
    password: seynur2462736
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

telegrambot:
  userName: "@tour_app_bot"
  botToken: 1851213801:AAHPc1W4pflBrlqFZNCPq4uWn_DZ8qxXTbU
  webHookPath: https://4fd1b73b0a7b.ngrok.io
  telegramUrl: https://api.telegram.org/bot
  botPath: webhook

redis:
  host: localhost
  port: 6379
offer:
  sentCount: "5"
  responseLimit:
    days: "0"
    hours: "0"
    minutes: "5"
  image:
    path: "images/"
    extension: ".jpg"
cron:
  waitingAnswerScheduler: "0 * 00-23 * * ?"