spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
telegrambot:
  userName: "@tour_app_bot"
  botToken: 1851213801:AAERzLNwhjZVDYtkIX6FdJmZxKX4EodDvLk
  webHookPath: https://tour-telegram-bot.herokuapp.com/
  telegramUrl: https://api.telegram.org/bot
  botPath: webhook

offer:
  sentCount: "5"
  image:
    path: "images/"
    extension: ".jpg"
